### ISSUE TITLE
OSMC installation

### ISSUE THREAD

**Issue by ChriZathens** [nirvana-7777/pvr.eon#8]
Would someone kindly let me know of the steps I need to take in order to install on a raspberry pi 3b running OSMC?
I have tried the version pvr.eon.21.7.6.linux.armv7a.zip found in [this kodinerds thread](https://www.kodinerds.net/thread/77069-release-pvr-eon-tv/), using the install from zip method, but it failed to install
Thanks in advance

**Comment by nirvana-7777** [comment]
Github is only for issues with the code. Please come tot the forum.
